### ISSUE TITLE
Refer to Process ID, not application by name?

### ISSUE THREAD

**Issue by bartwalczak** [BenZed/after-effects#16]
This module is really awesome.

Do you think there is a chance that you could make it possible to refer to the After Effects instance by process id, not by application name? This way it would be possible to open multiple instances of AE and communicate with them separately. Right now only a single instance is possible.

I don't know enough AppleScript to help, but I found this:
http://stackoverflow.com/questions/12332810/applescript-user-interface-scripting-how-to-tell-a-process-when-two-process

**Comment by BenGaumond** [comment]
This is a wonderful idea.

As it just so happens, for work I wrote a local module for starting and stopping a process based on it's id. I imagine it would be more difficult to make an equivalent function on windows, but I'll be sure to include it in the ES-6 refactor.

In the meantime, a workaround:

Inside your After Effects (assuming 2015.3) folder, copy the 'Adobe After Effects CC 2015' app and name it something else: 'Adobe After Effects CC 2015-2'

Each of these (and more, if you make further copies) can be opened as a separate instance of After Effects. For this module to take advantage of that, you have to explicitly set which application your code is going to. I suggest compiling separate commands:

`const ae = require('after-effects')

/* globals alert */

function sayMsg(message) {
  alert(message)
}

const msgToInstance1 = new ae.Command(sayMsg, {
  includes: [],
  program: '/Applications/Adobe After Effects CC 2015.3/Adobe After Effects CC 2015.app'
})

const msgToInstance2 = new ae.Command(sayMsg, {
  includes: [],
  program: '/Applications/Adobe After Effects CC 2015.3/Adobe After Effects CC 2015-2.app'
})

ae(msgToInstance1, 'Hello to instance 1')
ae(msgToInstance2, 'Hello to instance 2')
`

**Comment by bartwalczak** [comment]
Awesome! Thanks for that!
