### ISSUE TITLE
Use StandardJS.

### ISSUE THREAD

**Issue by hovosanoyan** [BenZed/after-effects#21]
I think StandardJS is best standard for NodeJS, so if you agree I will can change this code to SJS.

**Comment by BenZed** [comment]
I 100% agree with StandardJS, but you certainly don't have to go through the trouble.

I wrote this package quite a while ago, and it needs a once over. There's a development branch in the works, (it's been Idle for a while, but as coincidence would have it I need to update this package for work)

The rewrite will be SJS compliant!
